Traceback (most recent call last):
  File "/home/davide/.local/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/davide/.local/lib/python3.8/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/davide/.local/lib/python3.8/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/davide/.local/lib/python3.8/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/home/davide/.local/lib/python3.8/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/davide/.local/lib/python3.8/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import numpy as np
import matplotlib.pyplot as plt

#> Parameters
# E.g. Portfolio with 1-year return with expected value and variance 8%, 15%,
# 1-period withdrawal .04,, and initial value of the portfolio 1., like
# 40kâ‚¬ withdrawal of an initial portfolio of 1Mâ‚¬
wealth_ruin_exp = -3

#> Random number generator, representing 1-period return R_n = Y_{n}/Y_{n-1}
nreal = 2000       # n. of realizations of the random process
nt = 100           # n. of periods (toss) for each realization
tv = np.arange(nt)

#> Random number generators of the 2 assets
rng = np.random.default_rng().normal
rng_params = {'loc': mu, 'scale': sigma, 'size': nt}


------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[1], line 17[0m
[1;32m     15[0m [38;5;66;03m#> Random number generators of the 2 assets[39;00m
[1;32m     16[0m rng [38;5;241m=[39m np[38;5;241m.[39mrandom[38;5;241m.[39mdefault_rng()[38;5;241m.[39mnormal
[0;32m---> 17[0m rng_params [38;5;241m=[39m {[38;5;124m'[39m[38;5;124mloc[39m[38;5;124m'[39m: [43mmu[49m, [38;5;124m'[39m[38;5;124mscale[39m[38;5;124m'[39m: sigma, [38;5;124m'[39m[38;5;124msize[39m[38;5;124m'[39m: nt}

[0;31mNameError[0m: name 'mu' is not defined

